travis:
  secure:
    BINSTAR_TOKEN: L+eXKfQKrjThQIG9dKK71pMToyNBd5bOk7HUe3G071ZI39v7yRQ0BwVqOVhXD7q0ZBknFWEIMBk65LGEQvxzeJTKOjrJYV+xT6q9CRqrK14dOgpmmbn2+7IxyerRlA8Xf/Qq3zD7zjhW3AiVt1+TQlhNyXEteMUkhrlyGCGUzsrHV6bUmgEPl/KgzIXPiQ2U6Dz6T7q3eo8+p8AzZodDxUkSQwi+PwTue76hH1twJhnVUD+wmii8PfD2pAYq/LQgwD63yAWJbEDrFMi8qHaRd/KxkEu8xI4ST3BHbZrgAZo08DqeAWHXm8N56fJRF9Eyp34HEtyvqe0bde7p7sMAX2krrGXlOVMAs4NSYQ9KsQEgDE/XAQMGhPKUYw3JFg3KCRha6X9JLseGNNI1U0XYHXkNqbUqGbAqj+s6YiGdqXu+sC+9FAAOKFJRU870LlgdeQf1v4IqrOa5bd10Xr0uiMDjAWJQFJj+bny4oyhvObFmQ75Un+BNXVdwrIhiS9mrTA5uRh8Z2+G5xV0aJOgnHZ+5dxa/cf4PADfpfg19A/8I7jrdQp6fPK7Ac6trfydkz0AED/NL75IMSgn9lojy72gopefKnCjF172dFecB/0ZoYJ1V2LQCN+LlaKCnbE+y/Thn9fOO0gcUsrZASdYiro7ZFNA+I49dYJam1v8TDLg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
